### ISSUE TITLE
Process: sprint presentation + user testing

### ISSUE THREAD

**Issue by NB76** [InFact-coop/LCN#115]
Hi @maxgerber and @ivanmauricio,

I want to book a room and invite people for the presentation/user testing at the end of this sprint, which is on Tuesday (17 April). 

Should we go by how we did it last time? This would mean a two-hour slot (10:30am - 12:30pm) here at Tavis House, with potential users who have not been tested with before. Is this about right?

Thanks,

NB

**Comment by maxgerber** [comment]
That sounds good @NB76 - we might conceivably have slightly less to present here as the majority of the sprint is this login feature. Perhaps 11am - 12:30pm will do? Also, we will only

**Comment by NB76** [comment]
Yeah, saw that. Weird! 
Not sure about the stagger, ultimately people come when they do. I'll just have to entertain the ones not being tested. Let's book the room first!

**Comment by maxgerber** [comment]
@NB76 sounds good. I hope you have some good material

**Comment by NB76** [comment]
@maxgerber it's a bit dry, maybe not for everyone. But in the time-honoured tradition, when in doubt - offer food. It now transpires that there is no room available here from 11am, as this is the busiest time slot for meetings. We'll need to huddle in our office instead!

**Comment by NB76** [comment]
Looking forward to seeing you both here tomorrow. I've got people coming in from four different Law Centres, more weighted toward triage and management. See you soon!
