### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by NB76** [InFact-coop/LCN#136]
Hi @maxgerber,

Thanks for the Carlos user ID this morning, this got me in to sandbox what Carlos is set up as, which is a benefits caseworker. 

However, in order to review the copy in other pathways in light of your proposals, I would need either new profiles as management, reception, and other areas of law. Alternatively, I would need a way of resetting Carlos to be one of these things instead.  

Cheers,

NB

**Comment by maxgerber** [comment]
Hi @NB76,

Try going to https://lawcentres.herokuapp.com/#before-you-begin with Carlos logged in and you should be able to change what he is!

Best,
Max

**Comment by NB76** [comment]
Brilliant, thanks! More copy tweaks as per your proposals to come tomorrow. NB

**Comment by ivanmauricio** [comment]
Hi @NB76, just to let you know that the password resetting functionality is up and running so you should be able to reset your password to sign on to the app.

**Comment by NB76** [comment]
Brilliant, @ivanmauricio - now I can be Carlos AND myself!
