### ISSUE TITLE
Multi-select role types

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#138]
**Issue**: In some law centres, there are people who straddle the different role types. One common example is that many managers are also trained case workers and may take on an amount of case work in a working week.

**Solution**: 
 + Make the "Role type" buttons multi-select (checkboxes, not radio buttons).
 + Include a clarification ("You can select more than one").
 + On the AddStats page, combine sections from the form so that the person in question can fill in both

**Comment by NB76** [comment]
Just a note on the last bullet point: it needs to be clear on AddStats page which questions relate to which role. I'd suggest bunching them by role, distinguished by a divider line or some colour indication, whichever you think works better.

**Comment by maxgerber** [comment]
@NB76 good shout, yes I was thinking some kind of divider. I'll have a chat with @nogainbar about how best to implement that
