### ISSUE TITLE
Emphasis on introductions copy

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#140]
**Issue**: Some users worried they would be **unable to recall** the exact statistical information we were asking of them on first view of the **AddStats** page. Additionally, users **often skipped the intro text**, and as a result missed crucial information about what we were asking of them.

**Solution**: We should rewrite the copy, breaking it up with bolding/emphasis on important sections  to encourage people to actually read it! Specifically, on the AddStats page we should make clear that we are only asking for estimates and rough figures.

**Comment by NB76** [comment]
Suggested copy: "If you can't remember the exact number, your best estimate would do here."
