### ISSUE TITLE
Modal/Thank You Screen copy

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#144]
**Issue**: The wording of the "Thank You" screen came across as **ambiguous** in user testing. Most users described some confusion as to who was referred to by "we", and who was referred to by "your" (i.e. "With your help, we have seen 220 people this week").

**Proposal**: We will rethink this page to both make it feel relevant and clear for each role type
@NB76, we'd probably be able to change the statistic being shown depending on which role type the person is. Do you have some thoughts on
a) which statistic we should show for each role type (case worker, triage, management)
b) What the copy might be ("With your help...")
c) what copy would we show in the case of **multiple** role types?

**Comment by NB76** [comment]
I think 'you' is clear enough, it's the 'we' that wasn't - what I meant was Law Centres cumulatively, as I make clear below. 

For **caseworkers**, what was meant in it was "with your help, Law Centres have seen 330 [employment] cases this week" [change as applicable], followed by a pie chart breaking down case types by incidence [e.g. unpaid wages, unlawful dismissal, workplace discrimination...]. 

For **reception/triage** staff, copy would be "With your help, Law Centres have responded to [total no.] enquiries this week, which divide up as follows:"- - with a pie chart of distribution between: turned away, Law Centre casework, Law Centre one-off advice, referred to other agencies. Then add, "The most common agency Law Centres have referred to this week was [type as in tick boxes]".

For **management** staff, copy would be "With your Law Centre's help, Law Centres have involved [total no.] volunteers this week, dividing up as follows:" - - with a pie chart of distribution between students, lawyers and others. Then add, "[media total] Law Centres were covered in the media this week, and  there are currently [vacancy total] job opportunities across Law Centres."

Multiple roles are likely to be management with casework, and just like we asked them questions for both aspects, I would expect to tell them about both aspects, one after another.
