### ISSUE TITLE
Should we put less emphasis on the option to log out ?

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#145]
**Issue**:
Users recognised that at the Thank You/Success modal, we are giving them an option to bow out by offering log out. However, there was a discussion on whether we would want to put slightly less emphasis on logging out to encourage people to explore the Comments section.

@nogainbar, what do you think?

**Comment by NB76** [comment]
Suggestion: currently it presents the two options, 'see comments' and 'log out', at the same level/at par. Maybe instead we could have a more preferential approach: "What would you like to do now?"

- Check out and join the Law Centres discussion (in bold, in brand colour, perhaps larger font size)
- I'm done for now (line below, not bold, in default black, smaller font size)

Just a thought...

**Comment by maxgerber** [comment]
Hi @NB76 ,
I just had a chat with Noga, and she thinks that we should forgo all choice here, automatically redirect to the comments page after a few seconds, and then allow users to decide by either interacting with the comments or by logging out from the top navigation. What do you think?

**Comment by NB76** [comment]
That's a worthwhile nudge. We'll just need to make the 'log out' button prominent enough so they don't just close the window. And we'll need to amend the onboarding copy.
