### ISSUE TITLE
Ability to revise your statistics

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#146]
**Issue**: At present, people can't go back and revise the statistics they upload to Airtable if they feel they've made a mistake. 

**Solution**: Add an option to the fixed navigation bar to allow people to go back and and revise their statistics. This has the added benefit of offering "Privacy by design", by giving people greater control over the data they give to us.

(This will involve some back end work, and might be relegated to the backlog as a result of this)

**Comment by NB76** [comment]
This is one option. It might be simpler - if a tad more annoying - to go for two-stage approval: key in stats > 'Enter' > 'Confirm?'  ... or similar. I'd rather give them a chance to re-check before submitting than to revise submissions. Also, wouldn't revising submissions after the fact mess up the regular weekly reporting intervals?

**Comment by maxgerber** [comment]
@NB76, agreed!

**Comment by maxgerber** [comment]
Have added in @NB76's suggestion. Closing issue.
