### ISSUE TITLE
Primary areas of work 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LCN#15]
Hey @NB76,
As discussed yesterday we would like to find the primary area of work of the case workers/ staff. 
Can you advise what these are?

**Comment by NB76** [comment]
Primary ones:
- Housing
- Welfare Benefits
- Employment/Discrimination
- Immigration/Asylum
- Debt
- Public Law 
- Community Care

Additional ones (only a few have them, maybe make available under a context menu labeled 'other'?)
- Mental Health
- Consumer
- Family 
- Crime
- Education
- Youth legal advice

**Comment by Jen-Harris** [comment]
Perfect @NB76 thanks ! 👍
