### ISSUE TITLE
Point of order

### ISSUE THREAD

**Issue by NB76** [InFact-coop/LCN#30]
I am not clear about the next steps/timings, so let me ask. 

There was one day that you were going to come here and code, but I take it that it is not going to happen now? I'm out of the office tomorrow but have told @m4v15 that I can come into your Bethnal Green space in the afternoon. Would you like me to do that? 

There was going to be a 'presentation day' on Monday, but we didn't talk about format, location, participants etc. It's my first time with this and I don't know what to expect, so could you tell me more?

Unfortunately, Julie has to fly out to Australia this weekend as her mother is unwell, so if this has to involve her (as the CAST fellow), we may need to reschedule for the following week.

**Comment by Jen-Harris** [comment]
Hi @NB76,
Sorry for leaving you with lots of unanswered issues and questions today. I have had the day off and Matt, Noga and Ellie have been at another design day.
We will be working again on LCN tomorrow from 10am so will answer all your questions then!
Hope that's OK

**Comment by NB76** [comment]
No problem, @Jen-Harris, I'd just rather ask than assume. 
No rush tomorrow morning, I expect to only be back online from about 2:30pm but I'll be in Hackney so can pop in if needed.

**Comment by Jen-Harris** [comment]
Morning @NB76,

Don't worry about coming in today - we've got a lot to get through before Monday! If you did _*want*_ to come in however, please feel free.

In terms of the presentation unfortunately this cannot be postponed as we are on a very tight schedule with all the fellows. 

We are happy to come to your office at any time that is suitable for you on Monday for the presentation. 
The format will be:
* An overview of the problem
* A demo of the product
* Next steps 
* Feedback 
You can invite any colleagues that you feel would benefit from being there! 
Please let us know what time would suit you and if you have any further questions

**Comment by NB76** [comment]
Morning, @Jen-Harris! 

Monday at 10am seems to be the best time for us. As we'll be a smaller group, we'll just huddle in our office. Are 1-2 hours about right? 

Would there be a way for us to capture the presentation or at least share the demo itself with Ruth, Shyam and Sharon if they cannot join us? Their feedback would be valuable.

**Comment by Jen-Harris** [comment]
Hey @NB76, 
sounds great. It shouldn't be longer than an hour but that depends on how many questions you have!
We will build a short slide dec and it will all be very well documented with the repo for you to share with everyone else, so don't worry about that.
