### ISSUE TITLE
Individual (not rep) pathway: prioritise + further comments

### ISSUE THREAD

**Issue by NB76** [InFact-coop/LCN#35]
OK folks, I've had some late feedback from Julie. Essentially she is sceptical about the rep pathway because it is further away from the casework itself. She suggests asking caseworkers for a couple more details on their own work. This boils down to the following amendments:

In the 'what's your primary area of work' screen, add options 'manager' and 'reception/triage', both mid-way down.

Add another step between selecting area of work and the qualitative questions screen: this will ask a couple of simple quant questions.

In this stage, for everyone but 'reception/triage', ask: 
"how many people have you seen this week? New: ___ Ongoing: ___"
"types of problems seen: tick all that apply" - - here just mock up a multiple choice drop-down menu. At a later stage we can populate it with subcategories determined by the primary area of work they have chosen.
After they enter these figures, they go on to the qual screen (bugbears etc.)

In the same stage, only for 'reception/triage', ask:
"how many inquiries have you had this week? ___"
"how many people have you had to turn away this week? ___"
"types of problems you had to turn away: tick all that apply" - - here again just mock up a multiple choice drop-down menu: for now let the choices be 'legal aidable - no capacity', 'no legal aid - no capacity', and 'not covered by Law Centre'.
After they enter the figures, they go on to the qual screen (bugbears etc.)

Please prioritise these changes over the stuff I have sent yesterday for the quant/rep pathway. 

Thanks!

**Comment by NB76** [comment]
BTW sorry if it's the wrong label for this issue, still finding my feet...

**Comment by Jen-Harris** [comment]
Hey @NB76, 
Perfect use of an issue! 

This idea makes perfect sense and we will certainly focus more on the caseworker flow for the remainder of the spring. I'm not sure we'll have time include the questions in the coded prototype, but we'll let you know how we get on. However, we will try our best to get a static design of this flow ready to present on Monday to give an idea of how this could work!

**Comment by NB76** [comment]
That's fine, @Jen-Harris, as long as people get the feel of what it would be like.
