### ISSUE TITLE
Copy for Quantitative Questions

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#50]
Hi Nimrod @NB76, 

Our next stage now we've got the design and flow will be to think about the information we want displayed, and particularly the copy for the quantitative questions. As a vague rule,

What questions do you want the same for each "Area of law" ?
What extra questions would you like depending on the "Area of law" ?
How do you imagine these questions looking? (slider, checkbox, etc. We can advise you here if you're unsure)

Thanks!
Max

**Comment by NB76** [comment]
Hi Max,

Once a user selects the 'lawyer/caseworker' option, they will be given a drop-down menu for selecting their area of law (e.g. housing, immigration etc.).  

The primary quantitative questions about clients seen/new/repeat we have discussed as looking like a slider, which would encourage people to give their best estimate if they don't have a precise figure. These will be the same across all caseworker areas.

What will vary among the areas of law will be check boxes (allowing multiple selection) that would reflect the main problem themes for the area of law (e.g. in benefits they would be Universal Credit, ESA, PIP etc, in immigration they would be asylum application, asylum appeal, human trafficking, family reunification etc.). All very broad brush, just to get a gist of trends where they are not reported in the qualitative section.

The top-level categories of 'management' and 'triage/reception' would have entirely different quant reports to the above. More to follow on the detail for those. 

I am not wedded to my above guidance on look and feel. If you think of better options (the ultimate test is UX and engagement, isn't it?) please advise. 

Thanks, 

Nimrod

**Comment by maxgerber** [comment]
Hey Nimrod @NB76,

Thanks for the clarity on these, this is definitely something we can do. It would be great to get a list of examples for each area of law of what each checkbox would say. The more exhaustive list the higher fidelity the prototype will seem when we test.

That's fine, so we'll focus on the Case Worker route for now, and look towards management and reception once we have the copy.

I've addressed the design thinking behind the slider/no-slider debacle in [this issue](https://github.com/InFact-coop/LCN/issues/48), but essentially this came about after questions were raised about whether a slider would be demotivating to see at the end of the day if (for example) you only managed to see a couple of people that day, but had to turn away 30. I'm divided about this, so will defer to you. It's definitely an interesting point in terms of user testing...

Thanks,
Max

**Comment by NB76** [comment]
Hi @maxgerber 

I hope you've had a good weekend! 

Here is more about the caseworker quant questions. Across all areas of law, the questions were going to be, as before: How many clients have you seen this week? How many were new cases (can be a returning client)? How many were existing cases? 

Then, the tick boxes below would be contextual to each area of law. The guiding question is "What were the main kinds of PROBLEMS you have seen this week? Tick the top three."

For **welfare benefits**, tick boxes would be: entitlement, overpayment, right to reside, sanctions, Universal Credit, PIP, ESA, DLA, JSA, Council Tax Reduction, Tax Credit, Pension Credit.

**Employment**: working time, withheld wages/notice/holiday pay, redundancy payments, discrimination, breach of contract, unfair/constructive dismissal, disciplinary/grievance, whisteblowing. 

**Debt**: council tax arrears/bailiffs, utilities, rent arrears, mortgage (arrears or interest only), court fines, secured or student loans, credit card debt, overpaid benefits clawback.

**Housing**: allocations, committals, disrepair, duty scheme, eviction (incl. unlawful), homelessness, homelessness review, injunction, possession.

**Immigration and asylum**: asylum, non-asylum immigration, Article 8, Article 3/humanitarian protection, domestic violence, family reunion, NRPF/lifting, trafficking, children/UASC.

**Family**: care proceedings, child abduction, child arrangement orders, divorce, domestic violence, financial matters. 

**Community care**: aids and adaptations, assessments for care/support, best interest decision making, care/support planning, care at home, care home placement/supported living, carers assessment/services, Children's Act assessment/services,  payments (charging, personal budget, direct payments), service reorganisation/closure.

**Public law**: social welfare, human rights, migrant support, other.

On turning people away, the only ones to do so would be reception/triage staff, and they would sadly need to do that a lot. Still, this question would not be to caseworkers, so the potential demotivator of how many seen vs turned away is just not there. 

Cheers, 

@NB76

**Comment by maxgerber** [comment]
Hey @NB76,

Thanks for getting back with this! I have a slight concern that the amount of checkboxes for some of the areas of law might interfere with the cleanliness of the page - however, I'll see what I can do. If it looks a bit strange, how do you feel about culling the maximum number of checkboxes to... say... 6?

Regards,
Max

**Comment by NB76** [comment]
Whatever happened to "The more exhaustive list the higher fidelity the prototype will seem when we test"? ;-)

The lists were actually longer and more detailed, and I grouped them into fewer tick box categories. I take your point, though, that a balance needs to be struck between specificity and usability. Most areas of law have 10 at most, except benefits, where actually the first four are types of problem and the rest are kind of benefit they relate to. Maybe arranging them in two tick-box columns would do the trick and reduce the need to scroll down etc. 

I'm inclined to leave the lists as they are and get feedback in user testing on whether it's too much and what could be dropped.

**Comment by maxgerber** [comment]
Hi @NB76,
Fair enough! I actually agree with you on this, the checkboxes seem pretty crucial to the base functionality of the app, so I've left them in as you've suggested.

Regards,
Max
