### ISSUE TITLE
Copy needed for introductions to qual, quant forms and comments view

### ISSUE THREAD

**Issue by ivanmauricio** [InFact-coop/LCN#76]
Hi @NB76! Making good progress on the app. We need the final copy for a few different pages so that the app is ready for Friday's testing session. Could you let us know what copy you would like to have in the qual and quant forms and in the comments page? 

![screen shot 2018-02-20 at 15 59 11](https://user-images.githubusercontent.com/12462448/36434553-28f42db8-1657-11e8-9301-44c6fcc07265.png)
![screen shot 2018-02-20 at 15 59 35](https://user-images.githubusercontent.com/12462448/36434558-2bca79ac-1657-11e8-9db0-0118455ae210.png)
![screen shot 2018-02-20 at 15 59 50](https://user-images.githubusercontent.com/12462448/36434563-2dde3922-1657-11e8-9c8f-dde0ebe6f2d5.png)

**Comment by NB76** [comment]
I'll do these one screen at a go

**QUANT**

Introduction: 
"Please tells us a little about the cases you have seen this week. We are collecting this rough-and-ready information so LCN and each Law Centre have a better idea of current workloads and trends."
"This will help you see if your experience is similar to that in other Law Centres. It would also help LCN to speak out more quickly and with better authority about the issues arising." 

Survey questions:
"What is your role type at the Law Centre? 
Lawyer/caseworker
Triage/reception
Management"

If selected 'lawyer/caseworker' --> 
- "What is your main area of practice?"
- "Your week: if you don't remember exactly, give your best estimate" 
- "How many cases have you seen?"
- "Of these, how many cases were new? (Even if with a returning client)"

If selected 'reception/triage' -->
- "Your week: if you don't remember exactly, give your best estimate"
- "How many enquiries have you had this week in all? (include phone, email, in person)"
- "How many enquiries have you had to turn away without signposting anywhere?"
- "How many enquiries were signposted to one-off Law Centre advice? (include drop in or pro bono clinics)"
- "How many enquiries were referred to other agencies?"
- "Tick main types of agencies you referred to this week: 
- - Local advice agency 
- - Local non-advice support agency
- - National agency/helpline
- - Local MPs
- - Local councillors"

**Comment by NB76** [comment]
**COMMENTS/QUAL**

Summary:
"Tell us about the kind of things that you have seen this week; you can be as brief as you like, and submit as many or as few insights as you'd like. Here you can also ask or make a request of LCN. Answers, comments and replies all appear in the next section."

Trend:
"What trend(s) are you seeing at the moment? These can be declines or rises in certain types of problems, problem clusters, client groups. What is your hunch as to why this is happening?"

Success:
"Tell us about a case that you are proud of, or a client outcome that has made you particularly happy. We don't celebrate these good and inspiring moments enough. Let's change that!" 

Annoyance:
"What's got your goat this week? What policy or procedure have you come up against which you think is particularly crap? And what can be done to make it better?" 

Ask us:
"Have you got a question or a request for LCN? Let us know here and we will get back to you!"

**Comment by NB76** [comment]
**READ COMMENTS**

Summary:
"Here are the issues that Law Centres are seeing now, as shared by you! They are grouped by categories and the latest appear first. Feel free to reply to colleagues or simply 'like' their posts if they ring true. LCN responses to questions and requests are under the last heading." 

Here again, what's the 'ADD(?)' option at top right?

**Comment by ivanmauricio** [comment]
Thanks @NB76! Will start inputting copy in. As for your question...

> what's the 'ADD(?)' option at top right?

We've changed that to **Add a comment** and it is linking through to that section.

For the **Quant** section, what copy and questions would you like when they select **Management**?

**Comment by NB76** [comment]
Hi @ivanmauricio, the truth of the matter is that we have not thought this pathway through. Management perspectives will tend to be more overarching and qualitative. 
Therefore, please just put a placeholder text on the Management quant screen to say "What would you expect to be asked here?" Let's see what they say...

See you all tomorrow!
