### ISSUE TITLE
LCN assets

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/LCN#9]
@NB76 do you have any logo's or colour schemes for the LCN that we could use?

**Comment by NB76** [comment]
Sure, Matt, there you go: 

LCN Grey 
C:10 M:0 Y:0 K:70
R:122 G:125 B:132
HTML: 7a7d84

LCN Green 
C:100 M:0 Y:40 K:7
R:0 G:131 B:138
HTML: 00838a

LCN Blue 
C:100 M:70 Y:0 K:0
R:66 G:83 B:144
HTML: 425390

LCN Ruby Red 
C:0 M:100 Y:33 K:10
R:201 G:0 B:97
HTML: c90061

LCN Orange
C:0 M:75 Y:98 K:0
R:228 G:94 B:55
HTML: e45e37

And our logo: 
![lcn_rgb](https://user-images.githubusercontent.com/33842358/33035412-e9bbd1f4-ce22-11e7-9e39-f40cffb2e224.jpg)

**Comment by Jen-Harris** [comment]
Hey @NB76, thank you for this! 
Do you have the logo with a transparent background?

**Comment by NB76** [comment]
Jen, I have it as .TIF which cannot be pasted here - so here it is [on Dropbox](https://www.dropbox.com/sh/sdzljlesgb5xrvm/AAAoM02HAEelgumUjwTIsXpja?dl=0) instead.

**Comment by Jen-Harris** [comment]
This still seems to have a white background for me? 
No worries if you don't have one!

**Comment by NB76** [comment]
Funny, it doesn't to me here. I have it also in .EPS format, and those are all with transparent background. Can you/do you want to work with vector format?

**Comment by Jen-Harris** [comment]
Vector sounds great

**Comment by NB76** [comment]
Sure, it's in the same Dropbox folder now.
